### ISSUE TITLE
Failed to Deploy?

### ISSUE THREAD

**Issue by vinkla** [justpark/envoyer-deploy#4]
Seems I can't really deploy? Maybe I've missed something? I did add the service provider and the configuration file to my config directory.

```
file_get_contents(https://envoyer.io/deploy/https://envoyer.io/deploy/jkl6549sah321123…): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found            
```

**Comment by daylerees** [comment]
Looks like you inserted the full URL into the config, instead of just the token. :)

**Comment by vinkla** [comment]
Thanks :)
